feat: organization members
gamedaoco/gamedao-haiku pull request #245
Opened 2022-07-07 13:25 UTC by developer-sidani

## Related to issue #134 

### Done:

- Integrate the members for the organization
- Create a data grid for the members list
- Sort only Name and Role

### To Be Done:
- generate mock data and integrate it from GraphQL

#### Preview:

<img width="1185" alt="Screen Shot 2022-07-07 at 4 23 47 PM" src="https://user-images.githubusercontent.com/67205042/177784334-ade45d93-c1e5-4be8-b2df-5a9c21cc3bc7.png">

### How to Test:

- Navigate to an organization and check the members
- Join an organization and check if you are a member

2022-07-07 17:00 UTC, DarkNebula0 requested changes

2022-07-08 07:53 UTC, 5-mark commented
@developer-sidani : how about this AC:  
_"User: if verified show verified badge in front of name, if Identity is set show identity NAME, + wallet ID"_
So i miss the verified badge next to my address

![image](https://user-images.githubusercontent.com/91988132/177944643-a367af81-f998-4901-b6c5-5dc472710f1c.png)


vs.

![image](https://user-images.githubusercontent.com/91988132/177944668-e943eca6-1dee-4c0f-8611-75a6e174f4b5.png)

2022-07-08 09:06 UTC, 5-mark commented
@developer-sidani looks good now

2022-07-08 09:20 UTC, DarkNebula0 approved these changes

2022-07-08 09:20 UTC, merged