feat(page): campaigns list
gamedaoco/gamedao-haiku pull request #257
Opened 2022-07-12 11:30 UTC by developer-sidani

## Related to issue #230

### Done:
- Fetch Campaigns
- Display Campaigns
- Use translation for buttons and texts
- Apply pagination (only viewable when campaigns are over 15)

### To Do:
- Add search Bar
- Merge with main after PR for the campaigns list refactor
- Generalize the filters section for both organizations and campaigns page
- Filter query according to user input

2022-07-14 22:11 UTC, developer-sidani commented
> @developer-sidani please think of fallback images and can you avoid having campaign cards with different sizes?: ![image](https://user-images.githubusercontent.com/91988132/179047928-71b41e9f-9f59-4bd5-8cc9-1c044acdb3a6.png)

@5-mark This should be managed through the ticket responsible for the layout of the campaign card #247

2022-07-18 10:18 UTC, developer-sidani commented
PS: after discussion with @5-mark @2075 @DarkNebula0, there is not going to be filters for the target funded for this ticket, so definitely it is going to be managed by another ticket

2022-07-18 12:13 UTC, DarkNebula0 requested changes

2022-07-18 12:13 UTC, DarkNebula0 commented on pkg/app/src/pages/campaigns/index.tsx
> +		<Layout showHeader showFooter showSidebar title="Organisation">
Organization on the campaign site?

2022-07-18 12:13 UTC, DarkNebula0 commented on pkg/app/src/@types/campaign.d.ts
> +export interface CampaignsSortOptions {
Weren't they already created by graphql?

2022-07-18 12:51 UTC, 5-mark commented
@developer-sidani is it possible to set the default state of the filters like this:
![image](https://user-images.githubusercontent.com/91988132/179514854-529ac0be-f7ed-428a-be08-665ec0f8c357.png)
and the sorting default state for time left (the ones where least time is left on the top of the page, but not the ones where time is up already)

2022-07-18 14:09 UTC, DarkNebula0 approved these changes

2022-07-18 14:09 UTC, merged