feat: update avatar
gamedaoco/gamedao-haiku pull request #295
Opened 2022-07-20 11:50 UTC by hadi-ibra

### closes 285 
-----------------

Done:

- updated avatar on identity page
- updated avatar on organization members page

2022-07-20 12:57 UTC, DarkNebula0 requested changes

2022-07-20 12:57 UTC, DarkNebula0 commented on pkg/app/src/components/Account/modules/identitySection.tsx
> +	const avatarHash = md5(getAddressFromAccountState(accountState))
use useMemo

2022-07-20 12:57 UTC, DarkNebula0 commented on pkg/app/src/components/TabPanels/Organization/organizationMembers.tsx
> +										? `https://avatars.dicebear.com/api/pixel-art-neutral/${md5(
Simplify

	src={`https://avatars.dicebear.com/api/pixel-art-neutral/${md5(
												params?.row?.email || params?.row?.address,
										  )}.svg`
		    }

2022-07-21 08:49 UTC, hadi-ibra commented on pkg/app/src/components/Account/modules/identitySection.tsx
> +	const avatarHash = md5(getAddressFromAccountState(accountState))
notes

2022-07-21 08:58 UTC, hadi-ibra commented on pkg/app/src/components/TabPanels/Organization/organizationMembers.tsx
> +										? `https://avatars.dicebear.com/api/pixel-art-neutral/${md5(
yes noted

2022-07-21 09:04 UTC, hadi-ibra commented on pkg/app/src/components/TabPanels/Organization/organizationMembers.tsx
> +										? `https://avatars.dicebear.com/api/pixel-art-neutral/${md5(
yes noted

2022-07-21 09:04 UTC, DarkNebula0 approved these changes

2022-07-21 09:05 UTC, merged