5 mark/templates
gamedaoco/gamedao-haiku pull request #462
Opened 2022-10-25 14:42 UTC by 5-mark

update templates

2022-10-25 14:43 UTC, vovacha submitted a review, later dismissed

2022-10-26 18:54 UTC, 2075 requested changes

2022-10-26 18:54 UTC, 2075 commented on .github/ISSUE_TEMPLATE/Bug.md
> +labels: 'Bug'
would recommend to add the unverified label to an incoming bug which can be removed when one of us acknowledges the bug.

2022-10-28 20:10 UTC, 2075 commented on .github/ISSUE_TEMPLATE/Bug.md
> +labels: 'Bug'
@5-mark  ⬆️

2022-10-31 21:29 UTC, 2075 commented on .github/ISSUE_TEMPLATE/Bug.md
> +labels: 'Bug'
@5-mark

2022-11-01 10:43 UTC, 2075 approved these changes

2022-11-01 10:44 UTC, merged