feat(organisations): create organisations folder
gamedaoco/gamedao-haiku pull request #59
Opened 2022-03-28 23:46 UTC by sniper365

2022-03-31 10:22 UTC, DarkNebula0 requested changes

2022-03-31 10:22 UTC, DarkNebula0 commented on pkg/app/src/pages/app/organisations/index.tsx
> +	const { loading, data } = useBodiesQuery()
What happens when useBodiesQuery returns an error.
https://www.apollographql.com/docs/react/api/react/hooks/#usequery

2022-03-31 10:22 UTC, DarkNebula0 commented on pkg/app/src/components/OrganisationCard/item.tsx
> +export function Item({ data }) {
Missing parameter types(ComponentProps)

2022-03-31 10:22 UTC, DarkNebula0 commented on pkg/app/src/components/OrganisationCard/item.tsx
> +	const [metadata, setMetadata] = useState<any>()
Do not use any, unless absolutely necessary. 
there is a folder @types where you can create an interface for the metadata.

2022-03-31 10:22 UTC, DarkNebula0 commented on pkg/app/src/components/OrganisationCard/itemList.tsx
> +export function ItemList({ data }) {
Missing parameter types(ComponentProps)

2022-03-31 10:22 UTC, DarkNebula0 commented on pkg/app/src/components/OrganisationCard/modules/tileCard.tsx
> +	const SubHeader = () => {
Should be its own module.
Is inefficent, with each rerender the subhader is redefined.

2022-04-04 15:46 UTC, 2075 commented
@sniper365 please check https://www.conventionalcommits.org/en/v1.0.0/ as we rely on conventional commit messages to autogenerate changelogs.

2022-04-04 16:47 UTC, sniper365 commented
> 



> @sniper365 please check https://www.conventionalcommits.org/en/v1.0.0/ as we rely on conventional commit messages to autogenerate changelogs.

I will follow. Thanks.

2022-04-04 16:47 UTC, sniper365 commented
> 



> @sniper365 please check https://www.conventionalcommits.org/en/v1.0.0/ as we rely on conventional commit messages to autogenerate changelogs.

I will follow. Thanks.

2022-04-04 21:34 UTC, closed without merging